### ISSUE TITLE
about test

### ISSUE THREAD

**Issue by renminhooray** [akshitac8/BiAM#10]
in the code i can not find function named AttentionClassifier in the model file，what should I do? Thank you in advance

**Comment by akshitac8** [comment]
@renminhooray I have updated the evaluation file with the fix.

**Comment by unswchenyu** [comment]
I also met this problem. When I load pretrained weights files (model_best_gzsl.pth, model_best_zsl.pth)for openimages, I found error about "loading state_dict for BiAM", the reason maybe pretrained weights files for openimages are trained by **AttentionClassifier** but load by **BiAM** model? This is the error I met: 

RuntimeError: Error(s) in loading state_dict for BiAM:
        Missing key(s) in state_dict: "conv_3X3.body.weight", "conv_3X3.body.bias", "conv_3X3.bn.weight", "conv_3X3.bn.bias", "conv_3X3.bn.running_mean", "conv_3X3.bn.running_var", "region_context_block.w_q.weight", "region_context_block.w_q.bias", "region_context_block.w_k.weight", "region_context_block.w_k.bias", "region_context_block.w_v.weight", "region_context_block.w_v.bias", "region_context_block.w_o.weight", "region_context_block.w_o.bias", "region_context_block.sub_network.conv1.weight", "region_context_block.sub_network.conv1.bias", "region_context_block.sub_network.conv2.weight", "region_context_block.sub_network.conv2.bias", "scene_context_block.w_g.weight", "scene_context_block.w_g.bias", "scene_context_block.gcff.body.weight", "scene_context_block.gcff.body.bias", "scene_context_block.gcff.bn.weight", "scene_context_block.gcff.bn.bias", "scene_context_block.gcff.bn.running_mean", "scene_context_block.gcff.bn.running_var", "scene_context_block.channel_conv.body.weight", "scene_context_block.channel_conv.body.bias", "W.weight", "W.bias", "conv_1X1.body.weight", "conv_1X1.body.bias". 
        Unexpected key(s) in state_dict: "conv_layer1.body.weight", "conv_layer1.body.bias", "conv_layer1.bn.weight", "conv_layer1.bn.bias", "conv_layer1.bn.running_mean", "conv_layer1.bn.running_var", "conv_layer1.bn.num_batches_tracked", "self_attn1.query_conv.weight", "self_attn1.query_conv.bias", "self_attn1.key_conv.weight", "self_attn1.key_conv.bias", "self_attn1.value_conv.weight", "self_attn1.value_conv.bias", "self_attn1.out.weight", "self_attn1.out.bias", "ff1.conv1.weight", "ff1.conv1.bias", "ff1.conv2.weight", "ff1.conv2.bias", "W1.weight", "W1.bias", "conv_layer2.body.weight", "conv_layer2.body.bias", "vgg_net.W", "linear1.weight", "linear1.bias", "gcff.body.weight", "gcff.body.bias", "gcff.bn.weight", "gcff.bn.bias", "gcff.bn.running_mean", "gcff.bn.running_var", "gcff.bn.num_batches_tracked". 

The Missing key(s) are parameter name of **BiAM** and the Unexpected key(s) are parameter name of **AttentionClassifier**.
In addition, **AttentionClassifier** only found in openimages.log file and does not has model file has this function

**Comment by akshitac8** [comment]
@renminhooray @unswchenyu Does the error still comes while testing?
