### ISSUE TITLE
About Pretrained Weights

### ISSUE THREAD

**Issue by luoyixi924208423** [akshitac8/BiAM#16]
Thanks for your working.

I noticed that you mentioned pre trained model weights in the code. I have some interest in this,Could you realse the pretained weight in the GitHub or tell me how to pre-train the model.

thank you very much.

**Comment by akshitac8** [comment]
@luoyixi924208423 you can find the pertained weights in the readme here 
https://github.com/akshitac8/BiAM#step-3-evaluation-using-pretrained-weights-1

**Comment by luoyixi924208423** [comment]
> @luoyixi924208423 you can find the pertained weights in the readme here https://github.com/akshitac8/BiAM#step-3-evaluation-using-pretrained-weights-1

Thank you for your reply
