### ISSUE TITLE
Missing 81_only_full_nus_wide_train.json and 81_only_full_nus_wide_test.json files

### ISSUE THREAD

**Issue by MPR666** [akshitac8/BiAM#17]
Thanks for your great work and the code release.
I am now using your code (extract_nus_wide.py) to extract the features of the NUS-WIDE dataset, but I did not find the 81_only_full_nus_wide_train.json and 81_only_full_nus_wide_test.json files. Could you please provide these two json files?Thank you very much.

**Comment by sleepypineapple** [comment]
I have the same problem, how did you solve it

**Comment by AnishPawar** [comment]
I am also looking for the same json files. somebody please help
