### ISSUE TITLE
What's the size of OpenImagesV4 with 9m images?

### ISSUE THREAD

**Issue by Sen-Ran** [akshitac8/BiAM#21]
I tried to download OpenImagesV4 from the official website, but it shows that the OpenImagesV4 will costs about 18TB. Does this dataset really cost so much space?

**Comment by akshitac8** [comment]
It should be around ~1-1.5TB.

**Comment by Sen-Ran** [comment]
> It should be around ~1-1.5TB.

Thank you very much!
