### ISSUE TITLE
download pre-computed features Error404 

### ISSUE THREAD

**Issue by sorrowyn** [akshitac8/BiAM#3]
https://drive.google.com/drive/folders/1IBsJDS6eib_lA0yCBiGKL6enpzLv59Kt?usp=sharing

**Comment by akshitac8** [comment]
Hello @sorrowyn the link is fixed now :)

**Comment by sorrowyn** [comment]
![图片](https://user-images.githubusercontent.com/19569162/130975083-e453adfb-8567-4b24-a6a8-a82495650f2b.png)

thanks
