### ISSUE TITLE
About download_imgs. Py

### ISSUE THREAD

**Issue by sorrowyn** [akshitac8/BiAM#6]
No such file or directory:
1:labelmap_path=path+'classes-trainable.txt'
2:dict_path=path+'class-descriptions.csv'
3:df_label = pd.read_csv(path+data_set+'/annotations-human.csv')
4:df_image = pd.read_csv(path+data_set+'/images.csv')

**Comment by sorrowyn** [comment]
https://github.com/hbdat/cvpr20_LESA/tree/master/data/OpenImages/2018_04
![图片](https://user-images.githubusercontent.com/19569162/131302089-6ad76926-8f4e-4c00-98dc-6a9a348d1924.png)

**Comment by sorrowyn** [comment]
The download speed is too low to use proxy or not to use in china.

![图片](https://user-images.githubusercontent.com/19569162/131322925-70f3b373-a65b-441b-96c0-e65b0a19a746.png)
![图片](https://user-images.githubusercontent.com/19569162/131323006-714043ba-ba9e-497d-afac-63e05da0511e.png)

**Comment by akshitac8** [comment]
Hello @sorrowyn, Its not possible for us to upload the openimages dataset on the drive. for this you need to contact the openimages dataset authors. OpenImages generally takes anywhere around 1 to 2 weeks to download because it has to fetch from Flickr.

**Comment by sorrowyn** [comment]
> 
> 
> Hello @sorrowyn, Its not possible for us to upload the openimages dataset on the drive. for this you need to contact the openimages dataset authors. OpenImages generally takes anywhere around 1 to 2 weeks to download because it has to fetch from Flickr.
Thank you @akshitac8 for your reply. Can I use this method to download the openimages dataset?
https://github.com/cvdfoundation/open-images-dataset#download-images-with-bounding-boxes-annotations
![图片](https://user-images.githubusercontent.com/19569162/131349282-23e59799-3ebe-46ae-8837-9599a15f81f7.png)

**Comment by akshitac8** [comment]
Hello, @sorrowyn This will download data for the open-images detection dataset and not for classification. The detection dataset has training images of 1,743,042 while the classification has around 5M training files.

**Comment by akshitac8** [comment]
@sorrowyn is the issue solved?

**Comment by sorrowyn** [comment]
> 
> 
> @sorrowyn is the issue solved?
Hello,@akshitac8. I am currently testing. This problem can be solved with your help.d


![图片](https://user-images.githubusercontent.com/19569162/131643393-4c9c8805-1709-4ec4-986c-ec76e953f3dc.png)

**Comment by sorrowyn** [comment]
is 37600 images in  validation?
There are some errors:
1:<class 'PIL.UnidentifiedImageError'>
2:/home/XXX/anaconda3/envs/tensorflow/lib/python3.8/site-packages/PIL/Image.py:2911: DecompressionBombWarning: Image size (90642948 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.

pillow=8.3.1

![图片](https://user-images.githubusercontent.com/19569162/131646419-72cacc37-f0a4-46c3-b80b-68824bf5c2a0.png)

**Comment by akshitac8** [comment]
Hello @sorrowyn The no. of images will depend on how many are left on Flickr for the openimages dataset it can different from what we used. 
For pillow please try with v7.2.0

**Comment by sorrowyn** [comment]
![图片](https://user-images.githubusercontent.com/19569162/131837666-37334c97-ffee-409c-8dbd-2730382cf3fc.png)

**Comment by akshitac8** [comment]
@sorrowyn is the issue solved?

**Comment by sorrowyn** [comment]
Hi, akshitac@akshitac8! Thanks to your sincere help, the problem was solved.
______________________
pillow = 8.3.1
n_jobs = 32 in download_imgs. Errors occur when n_job is greater than 32

**Comment by akshitac8** [comment]
@sorrowyn happy to help :) I will be closing the issue now.

**Comment by NanAlbert** [comment]
Hello. @akshitac8 @sorrowyn  I also meet the problem "<class 'PIL.UnidentifiedImageError'>" and  "drop image", and it's also very slow. Can you provide detailed versions of any installed packages? Thanks a lot.
Some potentially important packages: 
h5py                    3.1.0
imageio                 2.0.1
importlib-metadata      4.8.3
joblib                  1.1.0
matplotlib              3.3.4
networkx                2.5.1
numpy                   1.19.5
opencv-python           4.5.5.62
pandas                  1.1.5
Pillow                  8.3.1
scikit-image            0.15.0
scikit-learn            0.24.2
scipy                   1.5.4
setuptools              59.6.0
requests                2.27.1
requests-oauthlib       1.3.1
![image](https://user-images.githubusercontent.com/36076117/155644799-593e65be-c7a5-457b-85de-32adb7b54d4a.png)

**Comment by Sen-Ran** [comment]
@NanAlbert Have you solved this problem?

**Comment by sorrowyn** [comment]
> @NanAlbert Have you solved this problem?

中间一部分数据无法下载，估计是连接失效了

**Comment by Sen-Ran** [comment]
@sorrowyn how many images have you already downloaded? and how much space did these images cost?

**Comment by Sen-Ran** [comment]
> > @NanAlbert Have you solved this problem?
> 
> 中间一部分数据无法下载，估计是连接失效了

Did you download into the 2018_04 folder or into the 2017_11 folder?
